name: Judge

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  judge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install supabase

      - run: python evaluator/judge.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - run: |
          git config user.name github-actions
          git config user.email actions@github.com

          git add docs/leaderboard.json
          git commit -m "update leaderboard" || exit 0
          git push